# Generated by Django 6.1.1 on 2026-10-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=64)),
                ('base', models.CharField(max_length=3)),
                ('quote', models.CharField(max_length=3)),
                ('direction', models.CharField(choices=[('above', 'above'), ('below', 'below')], max_length=5)),
                ('threshold', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_rate', models.FloatField(blank=True, null=True)),
                ('triggered_on', models.DateField(blank=True, help_text='Rate date that crossed the threshold', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
