# Generated by Django 6.1.1 on 2026-10-05 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=8)),
                ('in_ecb', models.BooleanField(default=True, help_text='False if ECB publishes no rate (AED)')),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=16)),
                ('ok', models.BooleanField()),
                ('rows', models.IntegerField(default=0)),
                ('latest_date', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('per_eur', models.DecimalField(decimal_places=10, max_digits=20)),
                ('source', models.CharField(choices=[('ecb', 'ECB via Frankfurter'), ('er_api', 'open.er-api.com'), ('derived_peg', 'Derived from USD peg')], max_length=16)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='rates.currency')),
            ],
            options={
                'ordering': ['date', 'currency'],
                'constraints': [models.UniqueConstraint(fields=('date', 'currency'), name='unique_rate_per_day')],
            },
        ),
    ]
